---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: w210
  namespace: w210jhand

spec:
  hosts:
    - "*"
  gateways:
    - istio-ingress/jonhand-gateway
  http:
    - match:
        - uri:
            exact: /predict
        - uri:
            prefix: /health
        - uri:
            prefix: /docs
        - uri:
            prefix: /openapi.json
      route:
        - destination:
            host: w210
            port:
              number: 8000
              
# ---
# apiVersion: networking.istio.io/v1beta1
# kind: VirtualService
# metadata:
#   name: w210
#   namespace: w210jhand

# spec:
#   hosts:
#     - jonhand.mids255.com
#   gateways:
#     - istio-ingress/jonhand-gateway
#   http:
#     - match:
#         - uri:
#             exact: /predict
#         - uri:
#             prefix: /health
#         - uri:
#             prefix: /docs
#         - uri:
#             prefix: /openapi.json
#       route:
#         - destination:
#             host: w210
#             port:
#               number: 8000


