apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapi-deployment
  namespace: w210jhand
  labels:
    app: pythonapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pythonapi-deployment
  template:
    metadata:
      labels:
        app: pythonapi-deployment
    spec:
      initContainers:
        - name: init-verify-redis-service-dns
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -vz redis-service 6379; do echo 'verifying redis DNS'; sleep 3; done",
            ]
        - name: init-verify-redis-ready
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until (printf 'PING\r\n';) | nc redis-service 6379; do echo 'verifying redis is up'; sleep 1; done",
            ]

      containers:
      - name: w210backend
        image: 621057158777.dkr.ecr.us-east-1.amazonaws.com/w210jhand:latest
        imagePullPolicy: Never
        env:
        - name: REDIS_URL
          value: "redis-service"
        ports:
        - containerPort: 8000
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
          httpGet:
            host:
            scheme: HTTP
            path: /health
            port: 8000
        livenessProbe:
          initialDelaySeconds: 5
          httpGet:
            path: /health
            port: 8000
          failureThreshold: 3
          periodSeconds: 60
          terminationGracePeriodSeconds: 60      
                     
        