apiVersion: v1
kind: Service
metadata:
  name: prediction-service
  namespace: w210jhand
spec:
  type: LoadBalancer
  selector:
    app: pythonapi-deployment
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
