apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: w210jhand
spec:
  type: ClusterIP
  selector:
    app: redis-deployment
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    
  
