---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: w210
spec:
  template:
    spec:
      containers:
        - name: w210
          image: 621057158777.dkr.ecr.us-east-1.amazonaws.com/w210jhand:latest
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 500Mi
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8000
            initialDelaySeconds: 1
            periodSeconds: 3
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
